### ISSUE TITLE
Blocking command example does not work (2.0.0a1)

### ISSUE THREAD

**Issue by bmerry** [aio-libs/aioredis-py#998]
Possibly this is just something that needs to be cleaned up in the documentation, but the example at https://aioredis.readthedocs.io/en/latest/examples/#blocking-commands fails with this error:

```
  File "blocking.py", line 33, in <module>
    asyncio.run(blocking_commands())
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "blocking.py", line 25, in blocking_commands
    await future
  File "blocking.py", line 20, in get_message
    with await redis as r:
AttributeError: __enter__
```

**Comment by Andrew-Chen-Wang** [comment]
Apologies, this should be resolved via latest. Follow the instructions in #930 to install on master.

**Comment by bmerry** [comment]
I've installed master (f12a6dc) and run the example code in master and it still fails as above.

**Comment by abrookins** [comment]
This looks like a docs typo. Shouldn't it be:

```python
        async with redis as r:
            return await r.brpop("my-key")
```
